### ISSUE TITLE
[M0 - Dev] Problema aclaración de la HU

### ISSUE THREAD

**Issue by pablo1mc315** [alvarogaro/AGR-MVS#10]
ISSUE enlazado con #3 

Buenas @alvarogaro. He estado dándole una vuelta, y me gustaría pedirte por favor si puedes modificar la HU para aclararla un poco. Me refiero:

- ¿Puedes aclarar un poco para qué va a usar el cliente (franquicia) la aplicación exactamente?
- Si el usuario va a utilizar la aplicación para elegir entre una tienda y otra por su tiempo en la cola, ¿no crees que debería estar en otra HU distinta?

A ser posible acláramelo por aquí, pero modifica también la HU si es necesario para que esté todo bien redactado y claro :)

**Comment by pablo1mc315** [comment]
No se te olvide asignar esta HU al M0 😁

**Comment by alvarogaro** [comment]
Buenas @pablo1mc315, respecto a la segunda pregunta, lo principal de esta aplicación va a ser el uso por parte de la empresa, por tanto la parte del usuario es algo que se tratará al final de la aplicación y como algo opcional, es por tanto que no he añadido una historia de usuario para ese caso en concreto. Respecto a la primera pregunta el cliente principal que va a ser la franquicia, lo que busca es una aplicación que introduciendo los diferentes datos que te he comentado en issues anteriores #7 va a poder coger todos los datos y con una serie de algoritmos de predicción que se trataran en  milestones  posteriores va a poder sacar conclusiones acerca de tiempos.

Espero que te haya ayudado, un saludo

**Comment by pablo1mc315** [comment]
Vale perfecto, en ese caso creo que no necesita modificación, mantengo la clase Usuario tal como está ya que en la HU lo mencionas, pero nada más.
