### ISSUE TITLE
[M0 - Dev] Cómo tratar el sistema de colas

### ISSUE THREAD

**Issue by pablo1mc315** [alvarogaro/AGR-MVS#11]
ISSUE enlazado con #3

Buenas @alvarogaro: 

- ¿Cómo tienes pensado gestionar el cálculo del tiempo que pasa una persona en la cola?¿Es algo que deba saber para la implementación de la estructura de datos?
- ¿Es necesario para esto que haya alguna clase más que gestione la estructura de la cola o basta con saber el tiempo medio que se pasa en ella?

**Comment by pablo1mc315** [comment]
Asigna también este issue al M0 :)

**Comment by alvarogaro** [comment]
Buenas @pablo1mc315, pues la implementación de las colas es algo que se tratará en milestones posteriores. creo que para este milestone no sería necesario

**Comment by pablo1mc315** [comment]
Esta bien saberlo, no modifico nada entonces!
