### ISSUE TITLE
[M1] Lógica De Negocio

### ISSUE THREAD

**Issue by alvarogaro** [alvarogaro/AGR-MVS#16]
En relación al milestone 1 y a la historia de usuario #3, vamos a tratar la lógica de negocio de nuestro problema. Principalmente nuestra lógica de negocio se basa en el análisis de las colas de los restaurantes con fin de mejorarlas. Para ello, será fundamental tratar con una serie de datos de los restaurantes que nos permitan realizar una análisis predictivo de los tiempos de colas que vamos a tener en ese restaurante.

Los restaurantes de comida rápida actualmente no tienen personal atendiendo en caja, todo se hace de manera electrónica mediante máquinas-kiosko o TPV. Por tanto el conjunto de datos que vamos a utilizar para desarrollar la lógica de negocio del problema van a provenir o ser deducidos principalmente de los tickets y datos registrados por estos kioskos.

**Comment by JJ** [comment]
Tampoco es un problema (y no entiendo el commit que se refiere a este issue)
