### ISSUE TITLE
[M0] Reestructuración modelo del problema 

### ISSUE THREAD

**Issue by alvarogaro** [alvarogaro/AGR-MVS#20]
* Tras haber planteado el PMV que queremos obtener en el issue #16, va a ser necesaria una reestructuración del modelo del problema que planteamos en el milestone 0, ya que tenemos clases que no van a ser necesarias, al igual que otras que son necesarios algunos atributos extra para almacenar datos.

**Comment by JJ** [comment]
Este issue no plantea ningún problema. Cualquier refactorización lo cerraría. Los issues deben plantear problemas.
