### ISSUE TITLE
[M0 - Dev] Elección del lenguaje de programación

### ISSUE THREAD

**Issue by pablo1mc315** [alvarogaro/AGR-MVS#4]
Buenas @alvarogaro !! Soy Pablo, JJ me ha asignado tu repositorio así que vamos a darle. Lo primero que todo es que me digas en que lenguaje de programación habías pensado hacerlo. Me dices y ya seguimos en contacto! :bowtie:

**Comment by alvarogaro** [comment]
Buenas @pablo1mc315 , pues en un principio, el profesor me dijo que era buena idea hacerlo en python, aunque también he estado considerando la opción de hacerlo en node.js, de cualquiera de esos dos elige el que quieras, o si tienes alguna otra sugerencia dímelo 🏌🏾‍♂️

**Comment by pablo1mc315** [comment]
No tengo problema con ninguno de los dos, me manejo bien en python y mi proyecto, de hecho, lo voy a hacer en node.js, pero creo que debes elegirlo tú ya que yo simplemente voy a trabajar en él en este objetivo. Informate un poco acerca de la ventajas de cada uno si quieres y me dices 💪

**Comment by alvarogaro** [comment]
Perfecto, he estado echando un ojo y finalmente me voy a decantar por python

**Comment by pablo1mc315** [comment]
Perfecto, en python entonces! Te abriré varios issues para consultar algunas cosillas acerca de la aplicacion
