### ISSUE TITLE
[M0 - Dev] Explicación de la lógica de negocio

### ISSUE THREAD

**Issue by pablo1mc315** [alvarogaro/AGR-MVS#6]
ISSUE enlazado con #3

Buenas @alvarogaro, he creado este ISSUE para que me expliques un poco cual es exactamente la lógica de negocio y me expliques un poco cual es el objetivo de la aplicación. He leído el fichero README, pero prefiero preguntarte para que no haya dudas :)

**Comment by alvarogaro** [comment]
Perfecto, pues basicamente lo que consiste la aplicación es en un predictor de las colas donde tienes un grupo de tiendas que pertenecen a una empresa, y para cada empresa tenemos una serie de datos relacionados con la gente que acude, tiempo en la cola, tiempo que tardan en ser servidos, numero de empleados que hay en ese momento... y a partir de estos datos, se va a generar una serie de informes respecto al tiempo que se estima que un usuario puede pasar en la cola. De esta manera la empresa puede llevar un control de la eficiencia de los empleados, ver que tiendas son las mas eficientes, y de cara a un usuario que quiere ir a una tienda a comer, permite saber que tiendas son las más rápidas para ahorrar el mayor tiempo posible

**Comment by pablo1mc315** [comment]
Vale, creo que lo entiendo. Voy crear una serie de issues para ir viendo como plantear la estructura de datos, pero entiendo que el objetivo principal de la aplicacion es el "estimar el tiempo que se pasa en la cola" a partir de todos esos datos, ¿cierto?

**Comment by alvarogaro** [comment]
@pablo1mc315 exactamente ese es el principal objetivo de la aplicación

**Comment by pablo1mc315** [comment]
Perfecto!

**Comment by JJ** [comment]
Esto debería haber acabado en una modificación del README.md y/o la historia de usuario. Modificar iv.yaml no tiene nada que ver. Si no está clara la lógica de negocio, es un problema, y todos los problemas deben resolverse con cambios en el código (o documentación, o ambos)
