### ISSUE TITLE
[M0 - Dev] Organización de la estructura de datos

### ISSUE THREAD

**Issue by pablo1mc315** [alvarogaro/AGR-MVS#7]
ISSUE enlazado con #3

Hola @alvarogaro. He estado dándole una vuelta y tengo varias dudas. En mi opinión, y según lo que me has indicado en #6, una empresa puede tener varias tiendas y, a su vez, una tienda puede tener varios empleados, ¿no es así? En ese caso, tendríamos:

## Estructura de clases

Voy a detallar un poco cuales serían las distintas clases de la estructura de datos y qué atributos contendrían, así que si no estás de acuerdo en algo dímelo y lo modificamos sin problema 👌🏼 .

### clase Empresa

- Nombre
- Listado de tiendas que posee esta empresa (podría ser una lista de datos de tipo Tienda).

### clase Tienda

- Nombre
- Empresa a la que pertenece (dato de tipo Empresa).
- Ubicación
- Número de trabajadores total
- Número de trabajadores en el momento
- Media de clientes al día
- Tiempo medio por pedido

### clase Empleado

- Nombre
- Apellidos
- Turno (puede ser un enum)
- Media de pedidos servidos por día

### clase Usuario

(aquí no se muy bien que poner, porque no se hasta que punto es necesario guardar los datos de los usuarios que utilizan la aplicación, así que dime que opinas y lo vamos viendo.  Lo que si creo que es que esta clase va a ser necesaria para implementar el algoritmo de estimación en el que se va a basar la lógica de negocio).

## Relaciones

- de uno a muchos entre Empresa y Tienda.
- de uno a muchos entre Tienda y Empleado (suponiendo que cada empleado trabaja en una única tienda, confírmame esto).
- de muchos a muchos entre Tienda y Usuario.

Coméntame que te parece y que cambiarías y me pongo a ello 💪🏼

**Comment by alvarogaro** [comment]
Hola @pablo1mc315 . La estructura la veo bien, en el caso del usuario realmente no sería necesario como dices guardar muchos datos, por tanto simplemente con que se guarde su localización de la ciudad donde se encuentra para que se le muestren tiendas de esa ciudad sería suficiente

**Comment by pablo1mc315** [comment]
Perfecto, ¿y al usuario le añado quizá usuario, contraseña y correo, ademas de la ubicacion? ¿o no es necesario que inicie sesion para utilizar la aplicación?

Y, el tipo de dato de la ubicacion, ¿lo trato como un string? No se exactamente como tratar este tipo de dato en python, si se te ocurre alguna manera dímelo o preguntamos al profesor

**Comment by alvarogaro** [comment]
Yo creo que no sería necesario que inicie, sesión, simplemente que ponga su ubicación y sería suficiente. Para el tipo de dato de la ubicación yo creo que estaría bien con un string pero de todas formas, dejalo para el final eso y le preguntamos al profesor

**Comment by pablo1mc315** [comment]
Perfecto! Pues me pongo con el código y te voy diciendo en el PR.

**Comment by pablo1mc315** [comment]
Hola @alvarogaro. Se me han ocurrido varias cosas para algunos de los objetos de la clase:

### clase Tienda

- ¿Crees que debería haber un array de los trabajadores que trabajan en cada tienda en vez del número total?
- ¿Crees que es necesario que guardemos otro array de los trabajadores que hay en cada momento? Lo digo porque este segundo debería ir cambiando en cada turno y no sería inmutable.
- ¿El tiempo medio por pedido debería ser un dato de la clase? En ese caso, también debería ir variando con el tiempo por lo que tampoco sería inmutable.

### clase Empleado

- Al igual que en la clase tienda, el tiempo medio de cada pedido debería ir variando, por lo que ya sería inmutable, y un empleado como tal no debería serlo ya que cada empleado es único. ¿Se te ocurre como podemos implementar esto?

### enum Turno

- ¿Te parece bien mañana, tarde, noche? No veo necesario tampoco especificar horas, ya que cada trabajador de la empresa sabrá cual es cada turno y en la mayoría de empresas se trabaja en base a esos 3 turnos.

### Creo necesario implementar otra clase en la que se realicen las estimaciones para implementar la lógica de negocio, pero tengo que darle una vuelta y pensar como hacerlo.

**Comment by pablo1mc315** [comment]
Perdona por la chapa, pero debo tener todo bien claro para poder implementarlo 🙃

**Comment by alvarogaro** [comment]
Buenas @pablo1mc315, te comento a ver como lo ves: 

* Enum Turno:  respecto al enum, veo bien esos turnos ya que son los principales turnos que tiene una tienda por tanto sin problema. Respecto a las horas, ya cuando se implementen las funciones de cálculo se hará la relación entre las horas y los turnos.
* Clase Empleado: Para esta clase, creo que simplemente será necesario almacenar el nombre del empleado y su ID de empleado para que sea único.
* Clase Tienda: Respecto a la Tienda, mi idea es que el numero de empleados que tenemos, sea un dato calculado cuando se haga el analisis. ( Me explico, teniendo la asociación que te he comentado, dentro de la clase tienda con la correspondencia entre empleado y turno, cuando vayamos a realizar los cálculos en etapas posteriores, se recorrería el enum y se almacenaría el numero de empleados que estan en mañana, luego en tarde y luego en noche y a partir de ahí ya se sacarían los resultados
*  En definitiva el array de empleados que hay en cada momento no sería necesario ya que lo sacamos luego en el calculo recorriendo el conjunto que va a tener cada objeto de tienda donde se encuentra la relación de empleado y turno.
* Luego respecto al tiempo medio de pedido, va a ser un dato también calculado, ya que lo que nos va a aportar realmente el csv, va a ser el numero total de pedidos que ha habido en cada turno, y la app ya se encargará posteriormente de realizar ese cálculo

**Comment by alvarogaro** [comment]
Te pongo un ejemplo para que quede mas clara la clase Tienda, segun el enfoque que quiero darle: 

Objeto Tienda: 
turnos = {Pedro:Mañana, Paco:Tarde, Maria:Tarde, Alberto:Noche, Pepe:Noche}
Pedido = {Mañana:20, Tarde:30, Noche:56} ( los numeros nos los va a dar el propio csv con los datos.)
A raiz de estos datos que tenemos que almacenar en Tienda, vamos a poder realizar posteriormente los cálculos de trabajadores que hay en cada momento y el tiempo medio por pedido por tanto no se almacenarán como datos de un objeto Tienda.

**Comment by pablo1mc315** [comment]
Vale, entonces para los turnos y para el pedido debería crear otra clase que guarde pares de valores por ejemplo:

- clase Turno: atributo Empleado y atributo Turno.
- clase TiempoPedidos: atributo Turno y atributo int.

¿O crees que basta con poner un tipo de dato diccionario de python que guarde ese par de valores y ya está?

Y respecto a la clase Empleado, ¿crees que es necesario un ID? Está la posibilidad de que se haya dos empleados con el mismo nombre pero, ¿no crees que es mas coherente algo como el DNI? Pero bueno, si lo ves bien con ID lo dejamos así, por mi perfecto.

**Comment by alvarogaro** [comment]
Buenas @pablo1mc315, simplemente con que pongas un diccionario sería suficiente, así evitamos tener demasiadas clases. Respecto a los empleados había pensado en un ID, ya que el DNI es algo personal que seguramente que en las bases de datos que encuentre no aparezca por privacidad

**Comment by pablo1mc315** [comment]
Perfecto, pues te voy diciendo!

**Comment by JJ** [comment]
¿Cómo puede estar esto cerrado si no se ha fusionado el PR? No puedes cerrar un issue desde el interfaz o te dará error a partir de ahora. *SIEMPRE* se cierra con un commit.
En todo caso, el issue no plantea un problema. Es uno de los items de a lista de comprobación, *que habéis marcado*. Efectivamente, no está asignado a una historia de usuario, lo que *no* habéis marcado. Siendo así, es simplemente una especulación sobre la sintaxis de una estructura de datos que nada tiene que ver con la resolución de un problema, y por lo tanto incorrecto tanto en sí como cualquier código al que haya dado lugar.
Por favor, tratad de seguir la metodología explicada en clase y que corresponde a las mejores prácticas en la industria.

**Comment by pablo1mc315** [comment]
@alvarogaro asigna este issue a la historia de usuario cuando puedas, te abro un par de issues para discutir ciertas cosas
