### ISSUE TITLE
[M0 - Dev] Objetivo de la aplicación

### ISSUE THREAD

**Issue by pablo1mc315** [alvarogaro/AGR-MVS#8]
ISSUE enlazado con #3

Buenas @alvarogaro, abro este issue porque no tengo muy claro cual es el objetivo final de la aplicación. Me explico: entiendo que la lógica de negocio es estimar el tiempo que se tarda en recibir un pedido en cada tienda, pero no entiendo si el objetivo de esta estimación es que el usuario elija una tienda u otra o que el "dueño" de la tienda tenga datos acerca de cada empleado, etc.

Te digo esto porque, si simplemente es para que el usuario elija una tienda no hay problema, bastaría con mostrar el tiempo estimado de cada una y ya está, pero si el objetivo, como has mencionado en HU0(#3), es que la empresa obtenga análisis de productividad acerca de cada tienda y cada empleado, habría que guardar todos los datos de cada uno de ellos, cobrando mucha más importancia la clase "empleado" que la clase "usuario", la cual tendría poca utilidad.

Aclárame un poco esto y cuando lo tenga claro te vuelvo a mandar una estructura de clases acorde al objetivo de la aplicación y ya me pongo a trabajar en ello.

**Comment by alvarogaro** [comment]
Buenas @pablo1mc315, la aplicación como comento en #3, esta prácticamente enfocada para la empresa, para el análisis tanto de las tiendas como de los empleados, por tanto, el usuario va a quedar en un segundo plano ( de hecho sería la ultima funcionalidad que va a tener la aplicación).

**Comment by pablo1mc315** [comment]
Perfecto, muchas gracias. Pues me pongo con el código y te voy diciendo!
