### ISSUE TITLE
[M0 - Dev] Base de datos de la aplicación

### ISSUE THREAD

**Issue by pablo1mc315** [alvarogaro/AGR-MVS#9]
ISSUE enlazado con #3 

Buenas @alvarogaro. ¿Has encontrado o tienes alguna BBDD a partir de la cual obtener los datos de las empresas? Si es así dime cual, para ir viendo los distintos valores que pueden tomar las variables.

**Comment by alvarogaro** [comment]
Pues estoy buscando algunas que tengan una estructura similar a como quiero plantear el problema

**Comment by pablo1mc315** [comment]
Vale, me vas diciendo por aquí, pero a ser posible cuanto antes mejor, para la implementacion de comprobaciones de datos y tal
